### ISSUE TITLE
add Check ServerID For every server !!

### ISSUE THREAD

**Issue by Drmohammad11** [sbpp/sourcebans-pp#427] opened 2018-03-24 08:08 UTC
i have 15 server from customers. if player banned from one server ,not ban all servers !!
not global ban !!

https://forums.alliedmods.net/showthread.php?t=305526

**Comment by Mr-Deej** [comment] 2018-03-24 10:33
The point of sourcebans is that it is a global ban management system

**Comment by Drmohammad11** [comment] 2018-03-24 12:25
That's right, but you can add the settings that can be changed
I and many vendors who do not require a global system!
I need to be a system that is just the same server as it was before, not all the servers we have.

**Comment by CrazyHackGUT** [comment] 2018-03-24 19:48
Just install SB more once. One server - one SB.

**Comment by Drmohammad11** [comment] 2018-03-25 02:35
i need web panel and can not install database and web panel for every server !
i have 15 servers, i will need 15 data base and 15 web panel  :( !!

It is possible to easily create settings in the web panel and plug-in to allow you to choose the type of system!

thank you RumbleFrog 👍

**Comment by good-live** [comment] 2018-03-25 06:46
It should be easy to filter the bans with the own server id in the sourcemod plugin or edit to add another WHERE condition to the SQL Query. However i would prefer a global and local ban system, which allows the admin to choose if the ban should be global or local or maybe even select the servers that the user should get banned from.

**Comment by rumblefrog** [comment] 2018-03-25 17:23
If I recall correctly, we were going to switch to a randomized server ID

**Comment by CrazyHackGUT** [comment] 2018-03-26 02:33
If you can move code from one source to another, you can try move this enhancement from my fork.

All required commits:
https://github.com/SB-MaterialAdmin/OldServer/commit/bfff600e7ba51cc5dedd2b364365464e014697fb
https://github.com/SB-MaterialAdmin/OldServer/commit/f40fc3e1ce430b644978837ddadc519e9925f5d7
https://github.com/SB-MaterialAdmin/OldServer/commit/af9583ff269f57551e2d9fae2cf312b4a2b353ae

P.S.: Translation for config:
```
		// Check the "ban source" before kick from server?
		//
		// 0 - not allow to connect, if ban exists on any server.
		// 1 - not allow to connect, if ban exists on this server or added from web-panel.
		// 2 - not allow to connect, if ban exists on this server.
```

**Comment by Groruk** [comment] 2018-06-17 14:34
Duplicate of #313

**Closed as completed by Groruk** 2018-06-17 14:34 UTC
Labels: type: enhancement, s: review needed, template: not used
