### ISSUE TITLE
Error when admin is IPv6

### ISSUE THREAD

**Issue by salasta** [sbpp/sourcebans-pp#416] opened 2018-03-12 06:03 UTC
Had an odd error when trying to add a ban or comm to SourceBans using the web interface. Managed to track down the issue to be a MySQL constraint.

## Expected Behavior
Add ban or comm to database.

## Current Behavior
Displays AJAX call error (HTTP request results in whitespace).
![ajax_error](https://user-images.githubusercontent.com/7445169/37267888-deff4202-2627-11e8-804a-b8817008d3b9.png)

Also error is displayed in System Log.
![logged_error](https://user-images.githubusercontent.com/7445169/37267887-ddbb74b0-2627-11e8-9328-0e00efcfefb9.png)

## Possible Solution
Change `adminIp` column in both `sb_bans` & `sb_comms` tables from `varchar(32)` to `varchar(45)`.
45 characters will also compensate for IPv4-mapped IPv6.

Only other solution would be to explicitly not support IPv6.

## Steps to Reproduce (for bugs)
1. Have IPv6 address
2. Add ban or comms

## Context
We use Cloudflare to proxy all of our requests; so it's not uncommon for `$_SERVER['REMOTE_ADDR']` to be an IPv6 address.

## Your Environment

* Version used: 1.6.1-git495
* PHP and MySQL version: php7.2, MariaDB 10.1.26
* Operating System and version: Debian 9

**Comment by rumblefrog** [comment] 2018-03-12 16:50
Duplicate of #340 and #161 

As discussed, since Valve doesn't support IPV6, it wouldn't make sense to support it.

Allowing IPv6 to be inserted would cause issues on the plugin side, and we would need to refactor the sleuth system. Until Valve or SM decides to support IPv6, we most likely won't implement support for it.

The solution, for now, is to force IPv4 on your web server.

**Closed as completed by rumblefrog** 2018-03-12 16:50 UTC
Labels: type: duplicate

**Comment by salasta** [comment] 2018-03-12 22:10
But this is just the admin's IP who banned the player not the player's IP.
Isn't the admin's IP only used for display in log so how would this effect the plugin?

**Comment by rumblefrog** [comment] 2018-03-13 01:20
So you want to mix the column? Because SM can't support fetching admin IP in IPv6 anytime soon. We would rather not have it if one could not support it
