### ISSUE TITLE
option to disable commbans message when players join the server

### ISSUE THREAD

**Issue by Xiaminou** [sbpp/sourcebans-pp#481] opened 2018-06-12 17:24 UTC
[This pull request](https://github.com/sbpp/sourcebans-pp/pull/398/commits/9b74a18be762485b99d7043f03b52d283d443f5b) adds a message that is displayed when someone with commbans joins the server. However if you have a lot of players with commbans on your server is ends up spamming quite a bit, and I've been told there is no option to disable it.

I suggest adding a cvar to disable these messages.

**Comment by rumblefrog** [comment] 2018-06-13 14:59
Comm checker was added by #398

**Comment by Groruk** [comment] 2018-06-17 14:10
Duplicate of #425

**Closed as completed by Groruk** 2018-06-17 14:10 UTC
Labels: p: low, type: enhancement, s: pending, template: not used
