### ISSUE TITLE
AJAX Call Failed !

### ISSUE THREAD

**Issue by krzys1540** [sbpp/sourcebans-pp#320] opened 2017-06-29 21:00 UTC
SourceBans++ 1.6.2-git526
When trying to add an admin pops up an error: AJAX Call Failed !
Error: the XML response that was returned from the server is invalid. Received: 
Fatal error: Uncaught exception 'Exception' with message 'There is no suitable CSPRNG installed on your system' in /home/p16516/public_html/sourcebans/includes/random_compat/lib/random.php:185 Stack trace: #0 /home/p16516/public_html/sourcebans/includes/CUserManager.php(280): random_bytes(32) #1 /home/p16516/public_html/sourcebans/includes/CUserManager.php(339): CUserManager->random_string() #2 /home/p16516/public_html/sourcebans/includes/sb-callback.php(1226): CUserManager->AddAdmin('abcdefg', 'STEAM_0:1:13123...', '', 'asdsad@wp.pl', -1, 0, 'Admin', '', 0, '') #3 [internal function]: AddAdmin('0', '', 'abcdefg', 'STEAM_0:1:13123...', 'asdsad@wp.pl', '', '', '1', '-3', '-1', '0', '0', '', ',s2') #4 /home/p16516/public_html/sourcebans/includes/xajax.inc.php(1095): call_user_func_array('AddAdmin', Array) #5 /home/p16516/public_html/sourcebans/includes/xajax.inc.php(744): xajax->_callFunction('AddAdmin', Array) #6 /home/p16516/public_html/sourcebans/index.php(33): xajax->processRequests() #7 {main} thrown in /home/p16516/public_html/sourcebans/includes/random_compat/lib/random.php on line 185
You have whitespace in your response.

**Comment by krzys1540** [comment] 2017-06-29 21:10
I changed php to version 7.0 and everything works: D

**Comment by rumblefrog** [comment] 2017-06-30 17:56
That's awesome! You should close this issue as you solved it and it's a duplicate of #261. Next time, follow our issue template, please 👍

**Closed as completed** 2017-06-30 23:46 UTC

**Comment by FuveZeq** [comment] 2021-02-12 18:17
krzys1540 And how?
