### ISSUE TITLE
Server not connecting to the web panel

### ISSUE THREAD

**Issue by KunnyestFid** [sbpp/sourcebans-pp#740] opened 2021-07-13 22:26 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. Add a server
2. Put the correct server info
3. Update the sourcemod.cfg properly and restart servers

What happens?
-------------
The servers don't connect to the webpanel

What were you expecting to happen?
----------------------------------
I was expecting them to connect to the webpanel

Any logs, error output, etc.?
----------------------------
Error connecting (<REDACTED IP>)

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System: Windows**
**SourceBans++ Version: 1.6.3**
**PHP Version: 7.2.38**
**MySQL Version: 5.7.31**
**Link to your project: ???**
**Link to a phpinfo() output: ???**

**Comment by distratul** [comment] 2021-08-07 06:24
I have the same problem...probably some ip connection that has been blocked from the administrator of web host.

**Comment by kamil445** [comment] 2021-11-01 11:32
SourceBans version 1.6.3 or newer require GMP Extenstion, in php.ini change
#extension=php_gmp.dll
to
extension=php_gmp.dll
(just remove #) and restart web server.
If you upgrade to SourceBans 1.6.4, you also need upgrade PHP to minimum 7.4, if you can;t upgrade PHP, stay on 1.6.3 and apply this patch for "error connecting" issue https://forums.alliedmods.net/showpost.php?p=2751644&postcount=6

for me worked :)

**Comment by crashzk** [comment] 2021-11-11 11:48
I believe it is a duplicate of these issues: https://github.com/sbpp/sourcebans-pp/issues/686

**Closed as completed** 2022-09-11 15:27 UTC
