### ISSUE TITLE
IPv6 Admin Issue (with solution)

### ISSUE THREAD

**Issue by andrewfer000** [sbpp/sourcebans-pp#690] opened 2020-08-28 18:49 UTC
What are the steps to reproduce this issue?
-------------------------------------------
1. Edit a ban as an Admin over IPv6
2. See that the ban was not created/edited
3. Look at the Sourcebans' log to see an PHP/SQL error

** I am submitting this on behalf of someone else **

What happens?
The ban does not update/change if the user is connecting via IPv6

What were you expecting to happen?
The ban works

Any logs, error output, etc.?
----------------------------
(I do not have admin access so I cannot view logs directly)

Any other comments?
I fixed the issue by changing the VCHAR length for the AdminIp column from 32 to 128 where applicable. I would suggest this be the default going into the future. 

What versions of software are you using?
----------------------------------------
**Operating System: Ubuntu 20.04 
**SourceBans++ Version: 1.6.3
**PHP Version: 7.2
**MySQL Version: MariaDB 10.2
**Link to your project: https://bananagaming.tv/bans/
**Link to a phpinfo() output: N/A

**Comment by rumblefrog** [comment] 2020-08-31 00:02
Duplicate of #416, #340, and #161

**Closed as completed by rumblefrog** 2020-08-31 00:02 UTC
