### ISSUE TITLE
Web does not work

### ISSUE THREAD

**Issue by Truba55** [sbpp/sourcebans-pp#265] opened 2017-04-26 09:39 UTC
If i open the Website "http://ravens-rising.de/sourcebans/ Gives this to me as an answer
```
xajax Error: xajax failed to automatically identify your Request URI.Please set the Request URI explicitly when you instantiate the xajax object.
```

* Version used: Version 1.6.0
* PHP and MySQL version: http://prntscr.com/f0z5ru
* Operating System and version: Windows Server 2016 #1607
* Link to your project: http://ravens-rising.de/sourcebans/

Other information:

I use a external Mysql database

**Comment by galexrt** [comment] 2017-04-26 15:31
Please run the following php script per web and post the output as a gist:
```
<?php
var_dump($_SERVER);
```

**Comment by Truba55** [comment] 2017-04-27 00:58
https://gist.github.com/Truba55/7d3eccd8fe4c474c20dc91180d179108

**Comment by galexrt** [comment] 2017-04-27 11:01
Comment the following lines https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/xajax.inc.php#L993-L994 and in the same file before the `exit();` (on line 995) add the following line:
```
var_dump($_SERVER);
```
Post the output of `/` page (comment when you have done it, so I can take a look at the page myself on your sourcebans installation too).

**Comment by Truba55** [comment] 2017-04-27 11:50
http://ravens-rising.de/sourcebans/

**Comment by galexrt** [comment] 2017-04-27 12:39
@Truba55 The problem is your IIS + PHP CGI installation, for the `sourcebans/` path, doesn't set "any" `$_SERVER` variables except `PHP_SELF` and `REQUEST_URI` (only to null). The `REQUEST_URI` is one of the required variables for the sourcebans ajax code.

**Comment by Groruk** [comment] 2017-04-28 11:26
Should be fixed now

**Comment by Groruk** [comment] 2017-04-28 11:27
Also please use issue #268 if you should have any further issues with this.

**Closed as completed by Groruk** 2017-04-28 11:27 UTC
Labels: p: low, type: question, s: in progress
